server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Video streaming untuk browser Smart TV / Coocaa
  location /videos/ {
    add_header Accept-Ranges bytes;
    add_header Cache-Control "public, max-age=86400";
    try_files $uri =404;
  }

  location ~* \.(mp4|webm|webp|png|jpg|jpeg|svg|ico)$ {
    add_header Accept-Ranges bytes;
    expires 1d;
    add_header Cache-Control "public, max-age=86400";
    try_files $uri =404;
  }
}
